### ISSUE TITLE
30 Minute 1 Topic redemption contract

### ISSUE THREAD

**Issue by isysd** [isysd/io-http-iramiller.com#15]
Write a contract that an individual would sign, which would allow redemption of their personal token in return for 30 minute meetings on a single topic.

The redeemer must define the discussion topic ahead of time.

The redeemee reserves the first 5 minutes of the 30 minute time slot for reading any documents or resources provided by the redeemer.

The after the 5 minute reading time, the next 20 minutes of the meeting are open for questions and discussion on the single topic.

The final 5 minutes of the meeting are reserved for closing discussion, arranging any follow up action items and notes.

Redemptions are made at a custom hourly rate _____ RATE, and sold in pro-rated 30 minute blocks, each costing RATE / 2.

Redemptions are subject to a 30 minute minimum purchase denominated in the redemees token. I.e. No less than RATE / 2 tokens may be redeemed at a time under this contract.

Redeemee reserves the right to define the method of conducting the meeting, including but not restricted to: physical location, phone, VOIP, video call.

The redemee may veto any redemption offer, or submit a counter-proposal, changing time but not redemption rate.

**Comment by kristine-osuna** [comment]
Submitted contract, please review and edit!
