### ISSUE TITLE
shave my beard redemption contract

### ISSUE THREAD

**Issue by isysd** [isysd/io-http-iramiller.com#18]
Write a contract that an individual would sign, which would allow redemption of their personal token in return for the redeemee shaving his beard.

Redemptions are made at a custom hourly rate _____ RATE, and sold in pro-rated 2 hour blocks, each costing RATE * 2.

Redemptions are subject to a 2 hour minimum purchase denominated in the redemees token. I.e. No less than RATE * 2 tokens may be redeemed at a time under this contract.

Redeemee reserves the right to define the location and tools used in the shaving.

The redemee may veto any redemption offer, or submit a counter-proposal, changing time but not redemption rate.

**Comment by statiamarieshillingford** [comment]
Contract submitted.
