### ISSUE TITLE
Advisor revenue share agreement

### ISSUE THREAD

**Issue by isysd** [isysd/io-http-iramiller.com#20]
Write a contract committing the Indvidual Token Issuer to a revenue share agreement with the Advisors.

____ SHARE_PERCENT will be set aside for the Advisor pool from all sales through the token issuance contract.

The Individual Token Issuer determines shares among the Advisor pool at their own discretion. The revenue share distribution must be made within 1 week of the end of the sale.

**Comment by isysd** [comment]
@Eldadbg @statiamarieshillingford @kristine-osuna This one is important for you all! ;)

**Comment by statiamarieshillingford** [comment]
Who is the Individual Token Issuer? Can you clarify the last paragraph please.

**Comment by isysd** [comment]
The person issuing the token, sorry. I am in this case.
