### ISSUE TITLE
Prepare to livestream from Panama Blockchain Embassy

### ISSUE THREAD

**Issue by isysd** [isysd/io-http-iramiller.com#28]
On Mon., Ira and friends will stream the #BirthdayICO live from the blockchain embassy. If possible, the full guld livestream setup should be moved to the embassy for the afternoon.

**Comment by isysd** [comment]
@lewi507 @ferdreyfus please help with this!

**Comment by ferdreyfus** [comment]
Live stream is ready and can be found here:
Starting at 2:00 P.M.

twitch.tv/guldblocktree  
https://www.facebook.com/guldblocktree/videos/1045533835613205/

**Comment by ferdreyfus** [comment]
https://www.youtube.com/watch?v=IaDSHtdltqM

https://www.youtube.com/watch?v=_KnKsBuIGk8

Broadcast was done and can be found here.
